
export class TramaHis {

    constructor( 
        public id: Number, 
        public codpaciente: string,
        public nrodocumentoPac: string,	
        public idtipodocPac: string,	
        public apepaternoPac: string,	
        public apematernoPac: string,	
        public nombresPac: string,	
        public nrohistoriaclinica: string,	
        public idsexoPac: string,	
        public fechanacimientoPac: string,
        public idetniaPac: string,	
        public idestablecimiento: string,	
        public idpaisPac: string,
        public idflag: string,	
        public codmedico: string,	
        public nrodocumentoMed: string,
        public idtipodocMed: string,	
        public apepaternoMed: string,	
        public apematernoMed: string,	
        public nombresMed: string,	
	    public idsexoMed: string,	
        public fechanacimientoMed: string,	
        public idpaisMed: string,	
        public idcondicion: string,	
        public idprofesion: string,	
        public nrodocumentoUsu: string,	
        public apematernoUsu: string,	
        public idpaisUsu: string,	
        public idprofesionUsu: string,
        public fechanacimientoUsu: string,	
        public nombresUsu: string,	
        public idtipodocUsu: string,	
        public apepaternoUsu: string,	
        public idsexoUsu: string,	
        public idcondicionUsu: string,
        public idups: string,	
        public annioedad: string,	
        public edadregistro: string,	
        public idtipedadregistro: string,	
        public mesedad: string,
        public diaedad: string,	
        public finan: string,	
        public idtipocondserv: string,	
        public idtipocondestab: string,	
        public peso: string,	
        public talla: string,	
        public hemoglobina: string,	
        public perimetrocefalico: string,	
        public perimetroabdominal: string,	
        public tipocita: string,
        public idcita: string,
        public aniocita: string, 
        public fechaatencion:string,
        public idturno: string,
         
        public periodo: string, 
    ){}                             
   
}
 